{{- if or (and .Values.grafana.enabled .Values.grafana.sidecar.datasources.enabled) .Values.grafana.forceDeployDatasources }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pyroscope.fullname" . }}-grafana-datasource
{{- if .Values.grafana.sidecar.datasources.annotations }}
  annotations:
{{ toYaml .Values.grafana.sidecar.datasources.annotations | indent 4 }}
{{- end }}
  labels:
    {{ $.Values.grafana.sidecar.datasources.label }}: "1"
    app: {{ include "pyroscope.fullname" $ }}-grafana
    {{- include "pyroscope.labels" $ | nindent 4 }}
data:
  pyroscope-datasource.yaml: |-
    apiVersion: 1
    datasources:
{{- if .Values.grafana.sidecar.datasources.defaultDatasourceEnabled }}
    - name: Pyroscope
      type: pyroscope-datasource
      isDefault: true
      jsonData:
        path: http://{{ include "pyroscope.fullname" . }}:{{ .Values.service.port }}
{{- end }}
{{- end }}